version: 2.1
jobs:
  build:
    docker:
      - image: cimg/base:2022.09
    steps:
      - checkout
      - run: sudo apt-get update && sudo apt-get install -y figlet
      - run: figlet "Continuous Integration Rocks!"
